#TRAEFIK crontab, 4 YAML files
apiVersion: batch/v1
kind: CronJob
metadata:
  name: traefik-logrotate-simple
  namespace: default
spec:
  # Run at 00:01 AM on the first day of every month
  schedule: "1 0 1 * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: logrotate-sa
          containers:
          - name: logrotate
            image: bitnamilegacy/kubectl:1.33.4
            command:
            - /bin/bash
            - -c
            - |
              echo "====== STARTING LOG ROTATION $(date) ======"
              
              
              echo "Stopping Traefik..."
              kubectl scale deployment traefik --replicas=0 -n default
              
              
              sleep 5
              
              
              echo "Moving log file..."
              cd /var/log/traefik
              
              YEAR=$(date -d "last month" +%Y)
              MONTH=$(date -d "last month" +%m)
              
              if [ -f "traefik-access.log" ]; then
                # Controlla se il file di destinazione esiste già
                if [ -f "oc-${YEAR}-${MONTH}.log" ]; then
                  EPOCH=$(date +%s)
                  TARGET_FILE="oc-${YEAR}-${MONTH}_${EPOCH}.log"
                  echo "File oc-${YEAR}-${MONTH}.log già esistente, creo: ${TARGET_FILE}"
                else
                  TARGET_FILE="oc-${YEAR}-${MONTH}.log"
                  echo "Creo nuovo file: ${TARGET_FILE}"
                fi
                
                mv traefik-access.log "${TARGET_FILE}"
                echo "Log spostato in ${TARGET_FILE}"
              else
                echo "No log file found"
              fi
              
              
              echo "Starting Traefik..."
              kubectl scale deployment traefik --replicas=1 -n default
              
              # Pulisci vecchi log (più di 5 anni)
              find /var/log/traefik -name "oc-*.log" -mtime +1825 -delete
              
              echo "====== ROTATION COMPLETED $(date) ======"
            volumeMounts:
            - name: logs
              mountPath: /var/log/traefik
              subPath: traefik
          restartPolicy: OnFailure
          volumes:
          - name: logs
            persistentVolumeClaim:
              claimName: nfs-log-dir-claim

---
# ServiceAccount for kubectl
apiVersion: v1
kind: ServiceAccount
metadata:
  name: logrotate-sa
  namespace: default

---
# permission to scale deployments on default namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: traefik-scale-role
  namespace: default
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["get", "patch", "update", "list"]

---
# Binding to default namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: logrotate-traefik-scale
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: traefik-scale-role
subjects:
- kind: ServiceAccount
  name: logrotate-sa
  namespace: default
############ END traefik crontab


---
# Varnish warmup script for Wordpress
apiVersion: v1
kind: ConfigMap
metadata:
  name: varnish-warmup-script
data:
  varnish-cache-warmer.sh: |
    #!/bin/bash
    VERSION='1.0.0'
    USER_AGENT="VarnishCacheWarmer"

    warm_varnish() {
        echo "Warming cache for $1"
        for i in {1..5}; do
          curl -sL -A "$USER_AGENT" http://$1/sitemap.xml | egrep -o "http(s?)://$1[^ \"\'()\<>]+" | while read line; do
              if [[ $line == *.xml ]]
              then
                  newURL=$line
                  curl -sL -A "$USER_AGENT" $newURL | egrep -o "http(s?)://$1[^ \"\'()\<>]+" | while read newline; do
                      time curl -sL -A "$USER_AGENT" -sL -w "%{http_code} %{url_effective}\n" $newline -o /dev/null 2>&1
                      echo $newline
                      sleep 2
                  done
              else
                  time curl -sL -A "$USER_AGENT" -sL -w "%{http_code} %{url_effective}\n" $line -o /dev/null 2>&1
                  echo $line
                  sleep 2
              fi
              sleep 2
          done
        done
        echo "Done warming cache for $1"
    }

    for host in "$@"; do
        warm_varnish $host
    done
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: wp-varnish-warmup
spec:
  schedule: "0 * * * *" # every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: wordpress-varnish-warmup
              image: alpine:latest
              command: ["/bin/sh"]
              args:
                - -c
                - |
                  apk add --no-cache bash curl grep && \
                  cp /scripts/varnish-cache-warmer.sh /tmp/warmer.sh && \
                  chmod +x /tmp/warmer.sh && \
                  bash /tmp/warmer.sh opencitations.net
              volumeMounts:
                - name: script-volume
                  mountPath: /scripts
          restartPolicy: OnFailure
          volumes:
            - name: script-volume
              configMap:
                name: varnish-warmup-script
# END varnish warmup script for Wordpress