apiVersion: apps/v1
kind: Deployment
metadata:
  name: oc-ldd
  namespace: default
  labels:
    app: oc-ldd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: oc-ldd
  template:
    metadata:
      labels:
        app: oc-ldd
    spec:
      containers:
        - name: oc-ldd
          image: opencitations/oc_ldd:${LDD_WEBSITE_VERSION}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: BASE_URL
              value: "${LDD_BASE_URL}"
            - name: META_HOST
              value: ${META_SERVICE_NAME}
            - name: META_PORT
              value: '1111'
            - name: META_USER
              value: ${META_USER}
            - name: META_PASSWORD
              value: ${META_DBA_PASSWORD}
            - name: INDEX_BASE_URL
              value: "${LDD_REDIRECT_BASE_URL}"
          resources: {}
          volumeMounts:
            - name: log-storage
              mountPath: /mnt/log_dir
      volumes:
        - name: log-storage
          persistentVolumeClaim:
            claimName: nfs-log-dir-claim
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
 name: oc-ldd-service
 namespace: default
 labels:
   app: oc-ldd
spec:
 selector:
   app: oc-ldd
 ports:
   - name: http
     port: 80
     protocol: TCP
     targetPort: 8080
 type: ClusterIP
---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
 name: oc-ldd
 namespace: default
 labels:
   app: oc-ldd
spec:
 entryPoints:
   - websecure
 routes:
   - kind: Rule
     match: Host(`${LDD_BASE_URL}`)
     services:
       - name: varnish-service
         port: 80
 tls:
   certResolver: myresolver
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
 name: oc-ldd-http-only
 namespace: default
 labels:
   app: oc-ldd
spec:
 entryPoints:
   - web
 routes:
   - kind: Rule
     match: Host(`${LDD_BASE_URL}`)
     middlewares:
       - name: redirect-to-https
     services:
       - name: varnish-service
         port: 80