apiVersion: v1
kind: Secret
metadata:
  name: traefik-acme-email
  namespace: default
type: Opaque
stringData:
  ACME_EMAIL: "${ACME_EMAIL}"
---
apiVersion: v1
kind: Secret
metadata:
  name: nfs-secrets
  namespace: default
type: Opaque
stringData:
  NFS_SERVER: "${NFS_SERVER}"
  NFS_CERT_PATH: "${NFS_CERT_PATH}"
  NFS_DATA_PATH: "${NFS_DATA_PATH}"