#### Comment this sections if you are not using HTTPS with ACME
additionalArguments:
  - '--certificatesResolvers.myresolver.acme.httpChallenge.entryPoint=web'
  - '--certificatesResolvers.myresolver.acme.email=${ACME_EMAIL}'
  - '--certificatesResolvers.myresolver.acme.storage=${ACME_PATH}'
  - '--entrypoints.web.forwardedHeaders.trustedIPs=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16'
  - '--entrypoints.websecure.forwardedHeaders.trustedIPs=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16'
  - '--entryPoints.websecure.http.encodequerysemicolons=true'
  - '--log.level=INFO'
  - '--accesslog.filepath=/var/log/traefik/traefik-access.log'
  - '--accesslog.format=json'
  - '--accesslog.fields.defaultmode=drop'
  - '--accesslog.fields.headers.defaultmode=drop'
  - '--accesslog.fields.names.ClientHost=keep'
  - '--accesslog.fields.names.DownstreamStatus=keep'
  - '--accesslog.fields.names.RequestHost=keep'
  - '--accesslog.fields.names.RequestPath=keep'
  - '--accesslog.fields.names.RequestMethod=keep'
  - '--accesslog.fields.names.StartUTC=keep'
  - '--accesslog.fields.headers.names.User-Agent=keep'
  - '--accesslog.fields.headers.names.Referer=keep'
  - '--accesslog.fields.headers.names.Authorization=keep'
  - '--accesslog.fields.headers.names.X-Forwarded-For=keep'
  - '--ping=true'

resources:
  limits:
    cpu: 4000m
    memory: 32Gi
  requests:
    cpu: 2000m
    memory: 4Gi

persistence:
  enabled: true
  accessMode: ReadWriteMany
  existingClaim: nfs-certificates-claim
  path: /acme
####

#### Comment this sections if you are not using NFS storage for logs
deployment:
  additionalVolumes:
    - name: traefik-logs
      persistentVolumeClaim:
        claimName: nfs-log-dir-claim

additionalVolumeMounts:
  - name: traefik-logs
    mountPath: /var/log/traefik
    subPath: ${NFS_LOG_TRAEFIK_SUBPATH}
####


#### Comment this sections if you are not using MetalLB
service:
 spec:
   externalTrafficPolicy: Local
 annotations:
   metallb.universe.tf/loadBalancerIPs: ${IP_RANGE_START}
####


logs:
  access:
    enabled: true
  general:
    level: INFO  